name: locora
description: "A clean, modern location pin icon with a subtle city skyline inside it, representing guided city exploration and discovery."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.3.0
  cloudinary_public: ^0.21.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  hugeicons: ^1.1.6
  image_picker: ^1.1.0
  shared_preferences: ^2.5.5
  google_maps_flutter: ^2.6.0
  geolocator: ^10.0.0
  random_avatar: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/locora.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
