// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuB_hJ64brSFm73X4Eaa1iWIXIzyg_14w',
    appId: '1:270432291898:web:355bb4899f37e490c43903',
    messagingSenderId: '270432291898',
    projectId: 'citi-guide-fire',
    authDomain: 'citi-guide-fire.firebaseapp.com',
    storageBucket: 'citi-guide-fire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7NZtnok6_y2dT-H7ZrLGXsfVGF0kwr3I',
    appId: '1:270432291898:android:d38a64df8ac1f7d2c43903',
    messagingSenderId: '270432291898',
    projectId: 'citi-guide-fire',
    storageBucket: 'citi-guide-fire.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuB_hJ64brSFm73X4Eaa1iWIXIzyg_14w',
    appId: '1:270432291898:web:3e231d79737605bac43903',
    messagingSenderId: '270432291898',
    projectId: 'citi-guide-fire',
    authDomain: 'citi-guide-fire.firebaseapp.com',
    storageBucket: 'citi-guide-fire.firebasestorage.app',
  );
}
